let audioContext;
export function h(html){const t=document.createElement('template');t.innerHTML=html.trim();return t.content.firstElementChild;}
export function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
export function toast(message,type='info'){const n=h(`<div class="toast toast-${type}" role="status">${escapeHtml(message)}</div>`);document.body.append(n);requestAnimationFrame(()=>n.classList.add('show'));setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.remove(),250);},1800);}
export function burst(anchor=document.body){const r=anchor.getBoundingClientRect?.()||{left:innerWidth/2,top:innerHeight/2,width:0,height:0};for(let i=0;i<14;i++){const p=h('<span class="particle">✦</span>');p.style.left=`${r.left+r.width/2}px`;p.style.top=`${r.top+r.height/2}px`;p.style.setProperty('--dx',`${(Math.random()-.5)*180}px`);p.style.setProperty('--dy',`${-40-Math.random()*130}px`);document.body.append(p);setTimeout(()=>p.remove(),900);}}
export function playTone(kind='tap',enabled=true){if(!enabled)return;try{audioContext||=new AudioContext();const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=({tap:440,correct:660,wrong:180,level:880,coin:740}[kind]||440);g.gain.setValueAtTime(.06,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.14);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.15);}catch{}}
export function createDragManager({cards,targets,onDrop}){const targetList=[...targets];cards.forEach(card=>{let ghost=null,pointerId=null,offsetX=0,offsetY=0;card.addEventListener('pointerdown',e=>{if(card.dataset.locked==='true')return;pointerId=e.pointerId;card.setPointerCapture(pointerId);const r=card.getBoundingClientRect();offsetX=e.clientX-r.left;offsetY=e.clientY-r.top;ghost=card.cloneNode(true);ghost.classList.add('drag-ghost');ghost.style.width=`${r.width}px`;ghost.style.height=`${r.height}px`;document.body.append(ghost);move(e.clientX,e.clientY);card.classList.add('dragging');e.preventDefault();});card.addEventListener('pointermove',e=>{if(ghost&&e.pointerId===pointerId)move(e.clientX,e.clientY);});card.addEventListener('pointerup',e=>{if(!ghost||e.pointerId!==pointerId)return;const target=targetList.find(item=>{const r=item.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});ghost.remove();ghost=null;card.classList.remove('dragging');if(target)onDrop(card,target);pointerId=null;});card.addEventListener('pointercancel',()=>{ghost?.remove();ghost=null;card.classList.remove('dragging');pointerId=null;});function move(x,y){if(ghost)ghost.style.transform=`translate(${x-offsetX}px, ${y-offsetY}px)`;}});}
export function modal({title,body,actions=[]}){const o=h(`<div class="modal-backdrop"><section class="modal-card" role="dialog" aria-modal="true"><h2>${escapeHtml(title)}</h2><div class="modal-body"></div><div class="modal-actions"></div></section></div>`);o.querySelector('.modal-body').innerHTML=body;const a=o.querySelector('.modal-actions');actions.forEach(action=>{const b=h(`<button class="btn ${action.primary?'btn-primary':'btn-secondary'}">${escapeHtml(action.label)}</button>`);b.addEventListener('click',()=>action.onClick?.(o));a.append(b);});document.body.append(o);return o;}
export function starsText(count){return `${'★'.repeat(count)}${'☆'.repeat(Math.max(0,3-count))}`;}
