import {renderShell} from '../ui/shell.js';
import {playTone,toast} from '../ui/components.js';
import {canPlacePiece,isBoardCovered} from '../math/advanced.js';
import {completeLevel} from './common.js';
const W=14,H=12,BASE=[['a',8,7],['b',6,7],['c',8,5],['d',6,5]];
export function renderRectanglePuzzle(root,ctx){let pieces=BASE.map(([id,w,h])=>({id,w,h,x:null,y:null,r:false})),hints=0,checks=0;const s=renderShell(root,ctx.state,{title:'🧩 14×12 長方形拼板',back:()=>ctx.navigate('#map'),content:`<section class="hero-card"><div class="npc">🧩</div><div><h1>把 168 格拼回去</h1><p>拖曳、旋轉、吸附四塊拼板，完整鋪滿 14×12。</p></div></section><section class="play-card"><div class="puzzle-status"><b>14×12 = 168</b><span data-status>不能重疊，也不能超出邊界。</span></div><div class="rectangle-board" data-board></div><div class="piece-tray" data-tray></div><div class="hint-row"><span data-feedback>點一下拼板可旋轉。</span><button class="btn btn-hint" data-hint>💡 提示</button></div><div class="action-row"><button class="btn btn-secondary" data-reset>重排</button><button class="btn btn-primary" data-check>檢查</button></div></section>`}),board=s.querySelector('[data-board]'),tray=s.querySelector('[data-tray]');
const d=p=>p.r?{w:p.h,h:p.w}:{w:p.w,h:p.h};const placed=id=>pieces.filter(p=>p.id!==id&&p.x!==null).map(p=>({...d(p),x:p.x,y:p.y}));
function draw(){board.innerHTML='';tray.innerHTML='';for(const p of pieces){const q=d(p),b=document.createElement('button');b.className='puzzle-piece';b.innerHTML=`<b>${q.w}×${q.h}</b><small>點一下旋轉</small>`;if(p.x===null)tray.append(b);else{b.classList.add('placed');Object.assign(b.style,{left:`${p.x/W*100}%`,top:`${p.y/H*100}%`,width:`${q.w/W*100}%`,height:`${q.h/H*100}%`});board.append(b);}wire(b,p);}}
function wire(b,p){let sx=0,sy=0,moved=false,g=null;b.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId);g=b.cloneNode(true);g.className='puzzle-piece piece-ghost';const r=b.getBoundingClientRect();g.style.width=`${r.width}px`;g.style.height=`${r.height}px`;document.body.append(g);move(e);e.preventDefault();});b.addEventListener('pointermove',e=>{if(!g)return;moved||=Math.hypot(e.clientX-sx,e.clientY-sy)>6;move(e);});b.addEventListener('pointerup',e=>{if(!g)return;g.remove();g=null;if(!moved){p.r=!p.r;if(p.x!==null){const q=d(p);if(!canPlacePiece({x:p.x,y:p.y,w:q.w,h:q.h},placed(p.id),W,H)){p.r=!p.r;toast('這裡不能旋轉。','error');}}draw();return;}const r=board.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){const q=d(p);let x=Math.round((e.clientX-r.left)/r.width*W-q.w/2),y=Math.round((e.clientY-r.top)/r.height*H-q.h/2);x=Math.max(0,Math.min(W-q.w,x));y=Math.max(0,Math.min(H-q.h,y));if(canPlacePiece({x,y,w:q.w,h:q.h},placed(p.id),W,H)){p.x=x;p.y=y;playTone('tap',ctx.state.settings.sound);}else toast('這裡會重疊。','error');draw();}else if(p.x!==null){p.x=p.y=null;draw();}});function move(e){if(g)g.style.transform=`translate(${e.clientX-g.offsetWidth/2}px,${e.clientY-g.offsetHeight/2}px)`;}}
s.querySelector('[data-hint]').onclick=()=>{hints++;s.querySelector('[data-feedback]').textContent=hints===1?'14 可以拆成 8+6。':hints===2?'12 可以拆成 7+5。':'上排放 8×7、6×7；下排放 8×5、6×5。';};s.querySelector('[data-reset]').onclick=()=>{pieces=BASE.map(([id,w,h])=>({id,w,h,x:null,y:null,r:false}));draw();};s.querySelector('[data-check]').onclick=e=>{checks++;const a=pieces.filter(p=>p.x!==null).map(p=>({...d(p),x:p.x,y:p.y}));if(a.length===4&&isBoardCovered(a,W,H)){playTone('correct',ctx.state.settings.sound);completeLevel({state:ctx.state,levelId:'rectangle-puzzle',accuracy:Math.max(.6,1-(checks-1)*.12),hintsUsed:hints,anchor:e.currentTarget,navigate:ctx.navigate});}else{s.querySelector('[data-status]').textContent='還有空格或位置不對。';playTone('wrong',ctx.state.settings.sound);}};draw();}
